spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diploma_project?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 329839
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # 显示 SQL 语句
    hibernate:
      ddl-auto: update # 自动更新表结构

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters-long
  expiration: 86400 # 24小时过期