spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diploma_project?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 329839
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # 显示 SQL 语句
    hibernate:
      ddl-auto: update # 自动更新表结构

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters-long
  expiration: 86400 # 24小时过期

logging:
  level:
    root: INFO # 设置全局日志级别为 INFO
    com.cms.reception: DEBUG # 设置项目包下的日志级别为 DEBUG
  file:
    name: logs/app.log # 日志文件路径
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 日志文件格式
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志格式