server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diploma_project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 329839
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# 七牛云配置
qiniu:
  # 访问密钥
  accessKey: dsjq5VLXslvh0YOn7MaHc0I8sGQcW51Z3HsN4OG9
  # 密钥
  secretKey: wX3cagWsnf93FIm5la38-k0tWSBSbkQ08HCt6Exb
  # 存储空间名
  bucket: uocms0012
  # 访问域名
  domain: svvrblb4c.hn-bkt.clouddn.com

jwt:
  secret: your_jwt_secret_key_here_make_it_long_and_secure_123456
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    root: INFO # 设置全局日志级别为 INFO
    com.cms.reception: DEBUG # 设置项目包下的日志级别为 DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  file:
    name: logs/app.log # 日志文件路径
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 日志文件格式
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志格式
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cms.reception.entity
file:
  upload:
    path: D:/upload/files  #  使用绝对路径
    url-prefix: /file/uploads

